autolabor_pro1:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint1

  joint2_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint2

  gazebo_ros_control:
    pid_gains:
      joint1:
        p: 100
        i: 1.0
        d: 0.1
      joint2:
        p: 100
        i: 1.0
        d: 0.1
