autolabor_pro1:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  front_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - frjoint
      - fljoint

  back_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints: 
      - brjoint
      - bljoint

  gazebo_ros_control:
    pid_gains:
      frjoint:
        p: 0.5
        i: 0
        d: 0
      fljoint:
        p: 0.5
        i: 0
        d: 0
      brjoint:
        p: 0.5
        i: 0
        d: 0
      bljoint:
        p: 0.5
        i: 0
        d: 0
