autolabor_pro1:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
