autolabor_pro1:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_controller:
    type: velocity_controllers/JointVelocityController
    joint: frjoint

  joint2_controller:
    type: velocity_controllers/JointVelocityController
    joint: fljoint

  joint3_controller:
    type: velocity_controllers/JointVelocityController
    joint: brjoint

  joint4_controller:
    type: velocity_controllers/JointVelocityController
    joint: bljoint

  gazebo_ros_control:
    pid_gains:
      frjoint:
        p: 100
        i: 1.0
        d: 0.1
      fljoint:
        p: 100
        i: 1.0
        d: 0.1
      brjoint:
        p: 100
        i: 1.0
        d: 0.1
      bljoint:
        p: 100
        i: 1.0
        d: 0.1
