autolabor_pro1:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  front_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - frjoint
      - fljoint

  back_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints: 
      - brjoint
      - bljoint

  gazebo_ros_control:
    pid_gains:
      frjoint:
        p: 100
        i: 1.0
        d: 0.1
      fljoint:
        p: 100
        i: 1.0
        d: 0.1
      brjoint:
        p: 100
        i: 1.0
        d: 0.1
      bljoint:
        p: 100
        i: 1.0
        d: 0.1
