autolabor_pro1:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  left_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - bljoint
      - fljoint
  right_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - brjoint
      - frjoint

  gazebo_ros_control:
    pid_gains:
      frjoint:
        p: 0.1
        i: 0.1
        d: 0
      fljoint:
        p: 0.1
        i: 0.1
        d: 0
      brjoint:
        p: 0.1
        i: 0.1
        d: 0
      bljoint:
        p: 0.1
        i: 0.1
        d: 0

