  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 100

  base_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50
    left_wheel: 'fljoint'
    right_wheel: 'frjoint'
    wheel_separation: 0.55
    wheel_radius: 0.124
    cmd_vel_timeout: 0.1
    base_frame_id: base_link
    enable_odom_tf: true
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    linear:
      x:
        has_acceleration_limits: true
        max_acceleration       : 2.5  # m/s^2
        min_acceleration       : -2.5

    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 20
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2

  gazebo_ros_control:
    pid_gains:
      frjoint:
        p: 10
        i: 0
        d: 0
      fljoint:
        p: 10
        i: 0
        d: 0

