  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 100

  base_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50
    left_wheel: ['bljoint', 'fljoint']
    right_wheel: ['brjoint', 'frjoint']
    wheel_separation: 0.45
    wheel_radius: 0.15
    cmd_vel_timeout: 0.1
    base_frame_id: base_link
    enable_odom_tf: true
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    linear:
      x:
        has_acceleration_limits: true
        max_acceleration       : 2.5  # m/s^2
        min_acceleration       : -2.5

    angular:
      z:
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2

  gazebo_ros_control:
    pid_gains:
      frjoint:
        p: 0.1
        i: 0
        d: 0
      fljoint:
        p: 0.1
        i: 0
        d: 0
      brjoint:
        p: 0.1
        i: 0
        d: 0
      bljoint:
        p: 0.1
        i: 0
        d: 0

