autolabor_pro1:

  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: bljoint
    right_wheel: brjoint
    wheel_separation: 0.46
    wheel_radius: 0.15
    cmd_vel_timeout: 0.1
    base_frame_id: base_link
    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  gazebo_ros_control:
    pid_gains:
      brjoint:
        p: 0.3
        i: 0
        d: 0
      bljoint:
        p: 0.3
        i: 0
        d: 0

